version: '3.3'
services:
  redis:
    image: redis:5.0.4
    restart: always
    ports:
      - 6379:6379
  stack-exchange-api:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 8080:8080