stackexchange.endpoint: http://api.stackexchange.com/2.2/

common:
  key: "1DDKQTupgyUC881vNPZp*g(("  #todo must be encrypted

spring:
  cache:
    type: redis
  redis:
    port: 6379
    host: localhost